project:
  type: book

  resources:
    - LICENSES/*.txt

profile:
  group:
    - [html, pdf, epub]

metadata-files:
  - _book-structure.yml

lang: es

book:
  title: "Ingeniería aumentada por sistemas inteligentes"
  author: "Javier G. Grandez"
  output-file: "iasi-book-III"

copyright:
  holder: "Javier G. Grandez"
  year: 2026

license: "CC BY"

filters:
  - iasi-plantuml

filter-options:
  plantuml:
    enabled: true
    server: http://localhost:10025
    cache: true
    styles:
      - resources/plantuml/iasi.puml
