project:
  output-dir: _outputs/html

website:
  announcement:
    content: |
      ![](/resources/images/ants.png){.iasi-ants-image}
    position: above-navbar
    dismissable: false

book:
  llms-txt: true
  page-footer:
    left: "© 2026 Javier G. Grandez · IASI Rocks 🤘"
    center: '<span id="iasi-publish-date"></span>'
    right:
      - text: "Licencias"
        href: 903-licenses.qmd

  sidebar:
    collapse-level: 1

  navbar:
    title: "IASI VOL. III"
    background: primary
    pinned: true
    
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Introducción"
        href: chapters/000-general/index.qmd
      - text: "Components"
        menu:
          - text: "Inputs"
            href: "chapters/010-inputs/index.qmd"
          - text: "Definitions"
            href: "chapters/020-definitions/index.qmd"
          - text: "Rules"
            href: "chapters/030-rules/index.qmd"
          - text: "Configuration"
            href: "chapters/040-configurations/index.qmd"
      - text: "Specifications"
        href: chapters/050-specifications/index.qmd
      - text: "Tasks"
        href: chapters/060-tasks/index.qmd
      - text: "No lo se"
        menu:
          - text: "Tasks"
            href: "chapters/060-tasks/index.qmd"
          - text: "Validations"
            href: "chapters/070-validations/index.qmd"
          - text: "States"
            href: "chapters/080-states/index.qmd"
          - text: "Automations"
            href: "chapters/090-automations/index.qmd"
      - text: "Transversal"
        menu:
          - text: "Skills"
            href: "chapters/100-skills/index.qmd"
          - text: "Commands"
            href: "chapters/110-commands/index.qmd"
          - text: "Templates"
            href: "chapters/120-templates/index.qmd"
          - text: "Workflows"
            href: "chapters/130-workflows/index.qmd"
      - text: "Adapters"
        href: chapters/200-adapters/index.qmd

    right:
      - icon: download
        text: "Guardar …"
        menu:
          - text: "Guardar …"
            href: "#iasi-exports"

      - icon: box-arrow-up-right
        href: "#iasi-open-external"
        aria-label: "Abrir en una pestaña nueva"

  search:
    location: navbar
    type: overlay

format:
  html:
    pagetitle: "IASI Vol. III"
    title-prefix: ""
    theme:
      - cosmo
      - resources/css/iasi.scss
      - resources/css/book.scss
    toc: true
