project:
  type: book

  resources:
    - LICENSES/*.txt
    
profile:
  group:
    - [html, pdf]

metadata-files:
  - _book-structure.yml

lang: es

book:
  title: "Ingeniería asistida por sistemas inteligentes"
  author: "Javier G. Grandez"
  output-file: "iasi"
  
  downloads:
     - pdf

  announcement:
    dismissable: false
    content: "![](/resources/images/ants.png){.iasi-ants-image}"
    type: light
    position: above-navbar

copyright:
  holder: "Javier G. Grandez"
  year: 2026

license: "CC BY"

filters:
  - iasi-plantuml

filter-options:
  plantuml:
    enabled: true
    server: http://javier:1025
    cache: true
    styles:
      - resources/plantuml/iasi.puml
      
