project:
  output-dir: _outputs/html

format:
  html:
    include-before-body: resources/html/banner.html
    theme: cosmo
    toc: true
    css: 
       -resoures/css/iasi.css
       -resources/css/book.css
    grid:
       body-width: 1440px
       